### ISSUE TITLE
Bug with menu editing

### ISSUE THREAD

**Issue by robiso** [StephanStanisic/plugin-plainadmin#1]
There seems to be a bug which renames existing pages to pages with prefixes.

Example/steps to reproduce
1. Install a clean version of WCMS.
2. Install plugin-plainadmin.
3. Open Settings -> General.
4. Click on "Home" (note that the previous slug was "home").
5. After page is refreshed, new slug is "home-1" and "home" doesn't exist any more.

**Comment by StephanStanisic** [comment]
Hmm, it seems that I'm not subscribed to my own repos! 

I'll see if I can reproduce this bug, it is weird since this only injects css and nothing else.

**Comment by StephanStanisic** [comment]
Just tested this and this is a problem that is also occurring without `plugin-plainadmin` installed, so this is probably something that's wrong in core.
